config/routes.rb
RailsBlog::Application.routes.draw do
  devise_for :users

   root 'posts#index'

  

	resources :posts

	resources :posts

	resources :comments, expect: :index
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId

	friendly_id :title, use: :slugged

	has_many :comments, dependent: :destroy

	validates_presence_of :title, :content

	def content
		super.html_safe
	end

	def self.search(search)
		if search
			where('lower(title) LIKE ?', "%#{search.downcase}%")
		else
			where(nil)
		end
	end

	def rating
		4
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    all_posts = Post.search(params[:search]).order('id DESC')
		@posts = all_posts.paginate(:page => params[:page], :per_page => 3)
		archive all_posts

		respond_to do |format|
			format.html
			format.js
		end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
		archive Post.all.order('id DESC')
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to '', notice: "Post #{@post.title} was successfully created." }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to '', notice: "Post #{@post.title} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    title = @post.title
		@post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post #{title} was successfully deleted."}
      format.json { head :no_content }
    end
	end

	def archive posts
		#TODO: Convert to a post creation-deletion driven archiving than redundant calculating one
		@months = Hash.new { |hash, key| hash[key] = [] }
		posts.each do |post|
			@months[post.created_at.strftime('%B, %Y')] << post.id
		end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params[:post].permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_archive.html.erb
<ul class="nav nav-list">
	<% @months.each do |key, value| %>
		<li class="nav-header" data-toggle="collapse" data-target="#<%= key.gsub(/[^0-9A-Za-z]/, '') %>">
			<span>
      	<i class="fa fa-plus-square-o"></i> <%= key + "(#{value.size.to_s})" %>
      </span>
			<ul class="nav nav-list collapse" id="<%= key.gsub(/[^0-9A-Za-z]/, '') %>">
				<% value.each do |id| %>
					<% post = Post.where(:id => id).first %>
					<li><%= link_to post.title, post %></li>
					<br/>
				<% end %>
			</ul>
		</li>
	<% end %>
</ul>

app/views/posts/_form.html.erb
<% @post ||= Post.new %>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.label :title %><br/>
	<%= f.text_field :title %><br/>
	<br/>

	<%= f.label :content %><br/>
	<%= f.text_area :content, :size => '80x20' %><br/>
	<!--<textarea id="post_content" placeholder="Enter text ..."></textarea>-->
	<br/>

  <button class="btn btn-warning btn-lg">Post</button>
<% end %>

app/views/posts/_post_listing.html.erb
<tr>
	<td>
		<div>
			<%= link_to "<h1 class='post-title'>#{post.title}</h1>".html_safe , post %>
			<div style="float: right">
				<% if user_signed_in? and current_user.author? %>
					<%= button_to edit_post_path(post), :method => 'get', :class => 'btn btn-primary' do %>
						<i class="fa fa-pencil-square-o"></i>
					<% end %>
					<%= button_to post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' do %>
						<i class="fa fa-trash-o"></i>
					<% end %>
				<% end %>
			</div>
		</div>
		<div>
			<button disabled class="btn post-details">Posted on: <%= post.created_at.strftime("%B %-d, %Y %l:%-M %P") %></button>
			<br/><br/>
		</div>
	</td>
</tr>
<tr>
	<td class="well post-content" align="justify">
		<%= post.content %>
	</td>
</tr>
<tr>
	<td align="center">
		<br/>
		<ul class="nav nav-list">
			<li class="nav-header" data-toggle="collapse" data-target="#<%= post.id %>">
				<span>
 	     	<button class="btn btn-info btn-lg openCommentModal" role="button"><%= pluralize(post.comments.count, 'comment') %></button>
 		     </span>
				<ul class="nav nav-list collapse" id="<%= post.id %>">
					<div id="<%= post.id %>">
						<hr class="style-five"/>
						<h3>Comments</h3>
						<% post.comments.each do |comment| %>
							<div class="well">
								<h4 class="comment-title"><%= comment.title %></h4>
								<div><button disabled class="btn post-details">Posted by <%= comment.user.email %> on <%= post.created_at.strftime("%B %-d, %Y %l:%-M %P") %></button></div>
									<h5 style="text-align: justify"><%= comment.content %></h5>
								<% if user_signed_in? and current_user.authorized? comment %>
									<%= button_to edit_comment_path(comment), :method => 'get', :class => 'btn btn-primary' do %>
										<i class="fa fa-pencil-square-o"></i>
										<% end %>
									<%= button_to comment, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' do %>
											<i class="fa fa-trash-o"></i>
									<% end %>
								<% end %>
							</div>
						<% end %>
						<div style="text-align: left">
							<% if user_signed_in? %>
								<div class="jumbotron">
									Add your comments below:
									<%= render 'comments/form', :post => post.id %>
									<!--<button class="openCommentModal btn btn-success" data-toggle="modal" data-target="#newComment" data-id="<%= post.id %>">Post a comment!</button>-->
								</div>
							<% else %>
								<%= button_to 'You must be logged in to post a comment!', '/users/sign_in', :method => 'get', :class => 'alert alert-danger' %>
							<% end %>
						</div>
					</div>
				</ul>
			</li>
		</ul>
	</td>
</tr>
<tr>
	<td><hr class="style-seven"/></td>
</tr>

app/views/posts/_posts_listing.html.erb
<div class="column three-fourth">
	<div class="table-responsive">
		<table>
			<tbody>
			<% posts.each do |post| %>
				<%= render 'post_listing', :post => post %>
			<% end %>
			<tr>
				<td align="center"><%= will_paginate posts %></td>
			</tr>
			</tbody>
		</table>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% content_for :title, "Welcome" %>
<form class="border" id="post-search" class="navbar-form navbar-left" role="search" action="<%= root_url %>">
		<!--<div class="form-group">-->
			<%= text_field_tag :search, params[:search], :placeholder => 'Start typing to search ... ', :class => 'form-control', :onclick => 'postSearch();' %>
		<!--</div>-->
</form><br/>

<% if user_signed_in? and current_user.author? %>
<button class="btn btn-success btn-lg" data-toggle="modal" data-target="#newPost" style="float: right"><i class="fa fa-plus-square-o"></i> Add a post!</button>
<% end %>
<br/>
<br/>
<br/>
<br/>

<div class="row">
	<div id="post-listing"><%= render 'posts/posts_listing', :posts => @posts %></div>
	<div class="column one-fourth well animation" style="float: right">
		<h2>My journey</h2>
		<%= render 'posts/archive' %>
	</div>
</div>

<br/>

<div class="modal fade" id="newPost" tabindex="-1" role="dialog" aria-labelledby="newPostLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="newPostLabel">Let those ideas flow!</h4>
			</div>
			<div class="modal-body">
				<%= render 'posts/form' %>
			</div>
			<!--<div class="modal-footer">-->
				<!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
				<!--<button type="button" class="btn btn-primary">Save changes</button>-->
			<!--</div>-->
		</div>
	</div>
</div>

app/views/posts/index.js.erb
$("#post-listing").html("<%= escape_javascript(render 'posts/posts_listing', :posts => @posts )%>")

app/views/posts/show.html.erb
<div class="column three-fourth">
	<div class="table-responsive">
		<table>
			<tbody>
				<%= render 'posts/post_listing', :post => @post %>
			</tbody>
		</table>
	</div>
</div>
<div class="column one-fourth well animation" style="float: right">
	<h2>My journey</h2>
	<%= render 'posts/archive' %>
</div>